version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: dev_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lifetrack
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: lifetrack-dev
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - '5555:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.6
    container_name: dev_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - '8080:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
